# Generated by Django 4.0 on 2022-03-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(verbose_name='Date')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('Count', models.IntegerField(verbose_name='Count')),
                ('Distance', models.IntegerField(verbose_name='Distance')),
            ],
        ),
        migrations.DeleteModel(
            name='DataBox',
        ),
    ]
