# Generated by Django 3.2.9 on 2021-11-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Имя')),
                ('last_name', models.TextField(max_length=200, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('department', models.TextField(max_length=100, verbose_name='Отдел')),
                ('program_language', models.TextField(max_length=200, verbose_name='Язык программирование')),
            ],
        ),
    ]
